version: "3"
services:
  mysql_8:
    container_name: mysql_svc
    image: mysql/mysql-server:8.0
    networks:
      - svc_net
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=  # database password
      - MYSQL_ROOT_HOST=  #set with the host that wants to access, set with '%' to allow access from all host
      # for another env, please refer to https://hub.docker.com/_/mysql
    volumes:
      - "./service_storage/mysql:/var/lib/mysql"

  mysql_5:
    container_name: mysql5_svc
    image: mysql/mysql-server:5.7
    networks:
      - svc_net
    ports:
      - "33065:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=  # database password
      - MYSQL_ROOT_HOST=  #set with the host that wants to access, set with '%' to allow access from all host
      # for other env, please refer to https://hub.docker.com/_/mysql
    volumes:
      - "./service_storage/mysql5:/var/lib/mysql"

  postgres_12:
    container_name: postgres_svc
    image: postgres:12.4-alpine
    ports:
      - "5432:5432"
    networks:
      - svc_net
    environment:
      - POSTGRES_DB=  # database name
      - POSTGRES_USER=  # database username
      - POSTGRES_PASSWORD=  # database password
      # for another env, please refer to https://hub.docker.com/_/postgres
    volumes:
      - "./service_storage/postgres:/var/lib/postgresql/data"

  redis_latest:
    container_name: redis_svc
    image: redis:latest
    ports:
      - '6379:6379'
    command: redis-server
    volumes:
      - './service_storage/redis:/data'

  minio_latest:
    container_name: minio_svc
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - "./service_storage/minio:/data"
    networks:
      - svc_net
    environment:
      - MINIO_ROOT_USER=  # minio username
      - MINIO_ROOT_PASSWORD=  # minio password
    command: server /data --console-address ":9001"

  portainer:
    container_name: portainer_svc
    image: portainer/portainer:latest
    ports:
      - "10000:8000"
      - "10001:9000"
    restart: always
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock" # docker socket file , https://docs.docker.com/engine/reference/commandline/dockerd/#daemon-socket-option
      - "./service_storage/portainer:/data portainer/portainer-ce"
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 9191:80
    networks:
      - svc_net
    environment:
      - MYSQL_ROOT_PASSWORD=  # database password
      - PMA_HOST= # database server host
      - PMA_PORTS=  # database server port

  sql-server-db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server:2017-latest
    ports:
      - "1433:1433"
    networks:
      - svc_net
    environment:
      SA_PASSWORD: ${PASSWORD}
      ACCEPT_EULA: "Y"

networks:
  svc_net:
    external: true