version: "3"
services:
  mysql_8:
    container_name: mysql_svc
    image: mysql/mysql-server:8.0
    networks:
      - svc_net
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=eucRvgVdaJMfY4G9R5KPwZ3V5g6pm8DP
      - MYSQL_ROOT_HOST=%
    volumes:
      - "./service_storage/mysql:/var/lib/mysql"

  mysql_5:
    container_name: mysql5_svc
    image: mysql/mysql-server:5.7
    networks:
      - svc_net
    ports:
      - "33065:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=eucRvgVdaJMfY4G9R5KPwZ3V5g6pm8DP
      - MYSQL_ROOT_HOST=%
    volumes:
      - "./service_storage/mysql5:/var/lib/mysql"

  postgres_12:
    container_name: postgres_svc
    image: postgres:12.4-alpine
    ports:
      - "5432:5432"
    networks:
      - svc_net
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=BZHnDem5mcbtJkk9YbZee787SyAFGy7x
    volumes:
      - "./service_storage/postgres:/var/lib/postgresql/data"

  redis_latest:
    container_name: redis_svc
    image: redis:latest
    ports:
      - '6379:6379'
    command: redis-server --requirepass wXU7z2HQtBP6mWjHbPsfK96rmnqweawg
    volumes:
      - './service_storage/redis:/data'

  minio_latest:
    container_name: minio_svc
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - "./service_storage/minio:/data"
    networks:
      - svc_net
    environment:
      - MINIO_ROOT_USER=AKIAIOSFODNN7EXAMPLE
      - MINIO_ROOT_PASSWORD=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    command: server /data --console-address ":9001"

  portainer:
    container_name: portainer_svc
    image: portainer/portainer:latest
    ports:
      - "10000:8000"
      - "10001:9000"
    restart: always
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./service_storage/portainer:/data portainer/portainer-ce"
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 9191:80
    networks:
      - svc_net
    environment:
      - MYSQL_ROOT_PASSWORD=eucRvgVdaJMfY4G9R5KPwZ3V5g6pm8DP
      - PMA_HOST=mysql_svc
      - PMA_PORTS=3306

  sql-server-db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server:2017-latest
    ports:
      - "1433:1433"
    networks:
      - svc_net
    environment:
      SA_PASSWORD: "eucRvgVdaJMfY4G9R5KPwZ3V5g6pm8DP"
      ACCEPT_EULA: "Y"

networks:
  svc_net:
    external: true